version: '3.4'

services:
  frontend:
    image: ziadmmh/bigoven-frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  backend:
    image: ziadmmh/bigoven-backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3000:80"