version: '3.4'

services:
  frontend:
    image: ziadmmh/bigoven-frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  backend:
    image: ziadmmh/bigoven-backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  reverseproxy:
    image: ziadmmh/bigoven-reverseproxy
    build:
      context: .
      dockerfile: reverseproxy/Dockerfile
    ports:
        - 80:80