version: '3.4'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

