name: Docker Images Build & Push to DockerHub

on: push

jobs:
  publish-container:
    name: Publish Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Publish bigoven-frontend to Docker Hub
      uses: docker/build-push-action@v1
      with:
        context: Frontend/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ziadmmh/bigoven-frontend
        tags: latest, ${{ github.run_number }}
    - name: Publish bigoven-backend to Docker Hub
      uses: docker/build-push-action@v1
      with:
        context: Backend/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ziadmmh/bigoven-backend
        tags: latest, ${{ github.run_number }}
